school/__init__.py
import os

from flask import Flask, render_template, url_for
from .frontend import frontend
from .config import Config
from .extensions import *
from .user import User, user
from .course import course
from .admin import admin
from .statistics import statistics


def create_app():
    app = Flask(__name__)

    # configure app
    app.config.from_object(Config)

    # configure extensions
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)
    toolbar.init_app(app)
    app.jinja_env.add_extension('jinja2.ext.do')

    # default login page, see https://flask-login.readthedocs.org/en/latest/#customizing-the-login-process
    login_manager.login_view = "frontend.login"

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    # configure blueprints
    blueprints = [frontend, user, course, admin, statistics]
    for blueprint in blueprints:
        app.register_blueprint(blueprint)

    # handle common error pages
    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template("errors/403.html"), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("errors/404.html"), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template("errors/500.html"), 500

    # static url cache buster, see http://flask.pocoo.org/snippets/40/
    @app.context_processor
    def override_url_for():
        return {"url_for": dated_url_for}

    def dated_url_for(endpoint, **values):
        if endpoint == 'static':
            filename = values.get('filename', None)
            if filename:
                file_path = os.path.join(app.root_path, endpoint, filename)
                values['q'] = int(os.stat(file_path).st_mtime)
        return url_for(endpoint, **values)

    return app

school/admin/__init__.py
# contains any CRUD not related to strictly editing users info and courses info
from .views import admin

school/admin/views.py
from flask.ext.login import login_required, current_user
from flask import Blueprint, render_template, flash, redirect, url_for, request
from school.decorators import role_required
from school.config import FLASH_SUCCESS, FLASH_ERROR
from school.models import *
from school.user import User

admin = Blueprint('admin', __name__)

@admin.route("/semesters")
@login_required
@role_required(admin=True)
def semesters():
    return "TODO"

# TODO add all the other views

school/course/__init__.py
# -*- coding: utf-8 -*-
from .views import course

school/frontend/__init__.py
# -*- coding: utf-8 -*-

from .views import frontend
from .forms import LoginForm

school/frontend/views.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, current_app
from flask.ext.login import login_required, logout_user, current_user, login_user
from .forms import LoginForm, PasswordResetForm, PasswordResetSubmitForm
from school.config import FLASH_SUCCESS, FLASH_INFO, FLASH_WARNING, FLASH_ERROR
from school.user.models import User
from school.extensions import *
from flask.ext.mail import Message

frontend = Blueprint('frontend', __name__)


@frontend.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated():  # user is already logged in
        flash("You are already logged in", FLASH_WARNING)
        return redirect(url_for('user.index'))

    form = LoginForm()
    if form.validate_on_submit():
        if form.remember_me.data:
            login_user(form.user, remember=True)
        else:
            login_user(form.user)

        return form.redirect("user.index")

    return render_template('frontend/login.html', form=form)


@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', FLASH_INFO)

    return redirect(url_for("frontend.login"))


@frontend.route('/password_reset', methods=["GET", "POST"])
def password_reset():
    token = request.args.get('token')

    # display password request form
    if token is None:
        password_reset_form = PasswordResetForm()
        if password_reset_form.validate_on_submit():
            email = password_reset_form.email.data
            user = password_reset_form.user
            if user is not None:

                # user has already a token present
                if User.verify_token(user.active_token):
                    flash("This email has a active reset password link still active. Please check your email spam folder.", FLASH_ERROR)
                    return render_template('frontend/password_reset.html', form=password_reset_form)

                # generate new token
                token = user.get_token()
                user.active_token = token
                db.session.add(user)
                db.session.commit()

                # send mail
                msg = Message('Reset password', sender='academicinfo.seproject@gmail.com', recipients=[email])
                msg.html = render_template('emails/password_reset_email.html', user=user, token=token)
                mail.send(msg)

                return render_template('frontend/password_reset_confirmation_sent.html')
        return render_template('frontend/password_reset.html', form=password_reset_form)

    # a token was given
    verified_result = User.verify_token(token)

    # given token is not valid
    if verified_result is None or verified_result.active_token is None:
        flash("It looks like you clicked on an invalid password reset link. Please try again.", FLASH_ERROR)
        password_reset_form = PasswordResetForm()
        return render_template('frontend/password_reset.html', form=password_reset_form)

    # the token is good
    password_submit_form = PasswordResetSubmitForm()
    if password_submit_form.validate_on_submit():
        # we make sure that the token is used only once
        verified_result.password = password_submit_form.new_password.data
        verified_result.active_token = None
        db.session.add(verified_result)
        db.session.commit()

        # send mail
        msg = Message('Your password has changed',
                      sender='academicinfo.seproject@gmail.com', recipients=[verified_result.email])
        msg.html = render_template('emails/changed_password_email.html', user=verified_result)
        mail.send(msg)

        flash("New password set successfully.", FLASH_SUCCESS)
        return redirect(url_for("frontend.login"))

    return render_template('frontend/password_reset_submit.html', token=token,
                           password_submit_form=password_submit_form)

school/statistics/__init__.py
from .views import statistics

school/statistics/views.py
from flask.ext.login import login_required
from flask import Blueprint, render_template, flash, redirect, url_for
from school.decorators import role_required
from school.config import FLASH_ERROR
from .forms import SelectStatisticForm, TeacherWBOWROStatisticForm, \
    OrderedStudentsStatisticFrom, \
    TeacherDisciplinesStatisticForm, Statistic
from school.models import *
from sqlalchemy import func, desc, distinct
from school.user import User

statistics = Blueprint("statistics", __name__)

# Statistics are available only for admins and chief departments.
@statistics.route('/statistics', methods=['GET', 'POST'])
@login_required
@role_required(admin=True, cd=True)
def see_statistics():
    form = SelectStatisticForm()
    if form.validate_on_submit():
        selected = form.selected_statistic.data
        if selected == Statistic.ORDERED_STUDENTS:
            return redirect(url_for('statistics.generate', statistic_id=selected))
        if selected == Statistic.TEACHER_RANKING:
            return redirect(url_for('statistics.generate', statistic_id=selected))
        if selected == Statistic.TEACHER_DISCIPLINES:
            return redirect(url_for('statistics.generate', statistic_id=selected))
    return render_template("statistics/see_statistics.html", form=form)


@statistics.route('/statistics/<int:statistic_id>', methods=["GET", "POST"])
def generate(statistic_id):
    if statistic_id == Statistic.ORDERED_STUDENTS:
        form = OrderedStudentsStatisticFrom()
        if form.validate_on_submit():

            subquery = db.session.query(User.id,
                                        User.realname.label("users_realname"),
                                        Group.name.label("groups_name"),
                                        func.avg(Enrollment.grade).label("average_mark"),
                                        Semester.year.label("semester_start_year")) \
                .join(Group.students) \
                .join(Enrollment).group_by(Enrollment.student_id).filter(Enrollment.grade > 0) \
                .join(degrees_period_students).join(DegreePeriod) \
                .join(Semester, Semester.id == DegreePeriod.semester_start_id)

            subquery_2 = None
            from_each = form.from_each.data
            # from each group
            if from_each == 0:
                subquery_2 = subquery.order_by("groups_name")

            # from each year
            elif from_each == 1:
                subquery_2 = subquery.order_by("semester_start_year")
            assert subquery_2 is not None

            subquery_3_result = None
            order_by = form.order.data
            # order by average mark (decreasing)
            if order_by == 0:
                subquery_3_result = subquery_2.order_by(desc("average_mark")).all()

            # order by name (alphabetically)
            elif order_by == 1:
                subquery_3_result = subquery_2.order_by("users_realname").all()
            assert subquery_3_result is not None

            lower_bound = form.average_mark_lower_bound.data
            upper_bound = form.average_mark_upper_bound.data

            # only take marks in specified range
            result_table = []
            for result in subquery_3_result:
                if lower_bound < result.average_mark < upper_bound:
                    result_table.append(result)

            if not result_table:
                flash("There is no data for this statistic", FLASH_ERROR)
            else:
                return render_template("statistics/ordered_students_statistic.html", from_each=from_each,
                                       order_by=order_by,
                                       lower_bound=lower_bound, upper_bound=upper_bound, result_table=result_table)
        return render_template("statistics/generate_statistic.html", statistic_id=statistic_id, form=form)

    elif statistic_id == Statistic.TEACHER_RANKING:
        form = TeacherWBOWROStatisticForm()
        if form.validate_on_submit():
            subquery = db.session.query(User.realname.label("users_realname"),
                                        Course.name.label("courses_name"),
                                        func.count(distinct(Enrollment.student_id)).label("no_of_students"),
                                        func.avg(Enrollment.grade).label("average_mark")) \
                .join(Teaches).join(Course).join(Enrollment).filter(Enrollment.grade > 0) \
                .join(User, User.id == Enrollment.student_id, aliased=True).group_by(Course.id)

            result_table = None
            best_0_or_worst_1 = form.criteria.data
            # it is wanted the teacher with the best results obtained
            if best_0_or_worst_1 == 0:
                result_table = subquery.order_by(desc("average_mark")).all()

            # it is wanted the teacher with the worst results obtained
            elif best_0_or_worst_1 == 1:
                result_table = subquery.order_by("average_mark").all()
            assert result_table is not None

            index = 0
            teacher_table = [result_table[index]]
            # in case there is more than one teacher with best/worst results obtained
            while result_table[index].average_mark == result_table[index + 1].average_mark:
                index += 1
                teacher_table.append(result_table[index])

            if not teacher_table:
                flash("There is no data for this statistic", FLASH_ERROR)
            else:
                return render_template("statistics/best_or_worst_teacher_results_statistic.html",
                                       best_0_or_worst_1=best_0_or_worst_1,
                                       teacher_table=teacher_table)
        return render_template("statistics/generate_statistic.html", statistic_id=statistic_id, form=form)

    elif statistic_id == Statistic.TEACHER_DISCIPLINES:
        form = TeacherDisciplinesStatisticForm()

        if form.validate_on_submit():
            selected_teacher_id = form.teacher_name.data

            # find teacher name
            teacher_name = None
            for choice in form.teacher_name.choices:
                if choice[0] == selected_teacher_id:
                    teacher_name = choice[1]
                    break
            assert teacher_name is not None

            statistics_table = db.session.query(Course.name.label("courses_name"),
                                                Course.type_id.label("courses_type"),
                                                Course.is_optional.label("courses_is_optional"),
                                                Degree.name.label("degrees_name"),
                                                Degree.type_id.label("degrees_type_id"),
                                                Language.name.label("languages_name"),
                                                func.count(distinct(Enrollment.student_id)).label("no_of_students")) \
                .group_by(Course.id).join(Teaches).join(Degree).join(DegreePeriod).join(Language) \
                .join(Enrollment, Enrollment.course_id == Course.id) \
                .join(User, User.id == Enrollment.student_id) \
                .filter(Teaches.teacher_id == selected_teacher_id).all()

            if not statistics_table:
                flash("There is no data for this statistic", FLASH_ERROR)
            else:
                return render_template("statistics/teacher_disciplines_statistic.html", teacher_name=teacher_name,
                                       statistics_table=statistics_table)

        return render_template("statistics/generate_statistic.html", statistic_id=statistic_id, form=form)

    # default page
    return redirect(url_for('statistics.see_statistics'))

school/user/__init__.py
# -*- coding: utf-8 -*-

from .views import user
from .models import User

school/user/views.py
from flask.ext.login import login_required, current_user
from flask import Blueprint, render_template, flash, redirect, url_for
from .forms import ChangePasswordForm, EditUserForm, AddUserForm
from .models import User
from school.config import FLASH_SUCCESS, FLASH_ERROR
from school.decorators import role_required
from school.extensions import db, mail
from flask_mail import Message

user = Blueprint('user', __name__)

# the root of our website
@user.route('/')
@login_required
def index():
    return render_template("user/index.html")


@user.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        flash('Password changed successfully.', FLASH_SUCCESS)
        current_user.password = form.new_password.data

        db.session.add(current_user)
        db.session.commit()

        msg = Message('Your password has changed', sender='academicinfo.seproject@gmail.com',
                      recipients=[current_user.email])
        msg.html = render_template('emails/changed_password_email.html', user=current_user)
        mail.send(msg)
        return form.redirect("user.index")

    return render_template('user/change_password.html', form=form)


@user.route('/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
@role_required(admin=True, cd=True)
def profile(user_id):
    user_instance = User.get_by_id(user_id)
    form = EditUserForm(obj=user_instance)
    if form.validate_on_submit():
        flash("Updated user details", FLASH_SUCCESS)

        form.populate_obj(user_instance)

        db.session.add(user_instance)
        db.session.commit()

    return render_template("user/user.html", user=user_instance, form=form)


@user.route('/user/delete/<int:user_id>')
@login_required
@role_required(admin=True, cd=True)
def delete(user_id):
    user_instance = User.get_by_id(user_id)
    if user_instance.id == current_user.id:
        flash("You can not delete yourself ;)", FLASH_ERROR)
        return redirect(url_for("user.users"))

    flash("User %s deleted" % user_instance.username, FLASH_SUCCESS)

    db.session.delete(user_instance)
    db.session.commit()

    return redirect(url_for("user.users"))


@user.route('/users', methods=['GET', 'POST'])
@login_required
@role_required(admin=True, cd=True)
def users():
    # CD can edit users only in this department

    form = AddUserForm()
    if form.validate_on_submit():  # add user

        # update database
        user_instance = User()
        form.populate_obj(user_instance)
        db.session.add(user_instance)
        db.session.commit()

        # update view
        form = AddUserForm()
        flash("User added", FLASH_SUCCESS)

    users_list = User.query.all()
    return render_template("user/users.html", users=users_list, add_form=form)

school/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=9"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{{ page_title|default('Project') }}{% endblock %} - Project</title>
    <link rel="Shortcut Icon" href="{{ url_for('static', filename='favicon.png') }}" type="image/x-icon">

    {% block css %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker3.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% endblock %}
</head>
<body>
<div id="body-wrapper">
    {% block header %}
        <header>
            <nav class="navbar navbar-default navbar-static-top navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
{#                        <a class="navbar-brand" href="{{ url_for('user.index') }}"><img src="{{ url_for('static', filename='favicon.png') }}" class="img-responsive" width="8%" height="8%"></a>#}
                           <a class="navbar-brand" href="{{ url_for('user.index') }}">AcademicInfo</a>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-right">
                            {% if current_user.is_authenticated() %}
                                <li role="presentation" class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                                        <b>{{ current_user.realname }}</b> <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="{{ url_for('course.see_courses') }}">See courses</a></li>
                                        {% if current_user.is_student() %}
                                            <li><a href="{{ url_for('course.contract') }}">Choose courses (contract)</a></li>
                                        {% else %}
                                            {% if current_user.is_chief_department() or current_user.is_admin() %}
                                            <li><a href="{{ url_for('course.establish_courses') }}">Manage optional courses</a></li>
                                            <li><a href="{{ url_for('statistics.see_statistics') }}">See statistics</a></li>
                                            {% else %}
                                            <li><a href="{{ url_for('course.establish_courses') }}">Add optional course</a></li>
                                            {% endif %}
                                        {% endif %}
                                    </ul>
                                </li>
                                <li role="presentation" class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                                        Settings<span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="{{ url_for('user.change_password') }}">Change password</a></li>
                                        {% if current_user.is_admin() %}
                                            <li><a href="{{ url_for('user.users') }}">Edit users</a></li>
                                        {% endif %}
                                    </ul>
                                </li>
                                <li><a href="{{ url_for('frontend.logout') }}">Log out</a></li>
                            {% else %}
                                <li><a href="{{ url_for('frontend.login') }}">Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    {% endblock %}
    <main class="container">
        {% block flash_message %}
            <div class="container-fluid">
                {% with messages = get_flashed_messages(with_categories=True) %}
                    {% if messages %}
                        <div class="container-fluid">
                            <div id='flash-message-container'>
                                {% for category, msg in messages %}
                                    <div class="alert alert-{{ category }}">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        {{ msg }}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                {% endwith %}
            </div>
        {% endblock %}
        {% block body %}
            <h1>CONTENT BODY NOT SET IN TEMPLATE, PLEASE SET IT!!!</h1>
        {% endblock %}
    </main>
    <footer>
        <p>© System for Managing Academic Information</p>
    </footer>
    {% block js %}
        <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.numeric.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap-datepicker.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/util.js') }}"></script>
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    {% endblock %}
</div>
</body>
</html>