school/admin/forms.py
from flask_wtf import Form
from wtforms import PasswordField, SubmitField, ValidationError, StringField, SelectField
from wtforms.validators import DataRequired, EqualTo, Email
from school.forms import RedirectForm
from flask.ext.login import current_user

class EditSemesterForm(Form):
    pass

class AddSemesterForm(Form):
    pass

class EditGroupForm(Form):
    pass

class AddGroupForm(Form):
    pass

class EditDepartmentForm(Form):
    pass

class AddDepartmentForm(Form):
    pass

class EditLanguageForm(Form):
    pass

class AddLanguageForm(Form):
    pass

# TODO maybe add teaches here?

school/course/forms.py
from flask_wtf import Form
from wtforms import SubmitField, BooleanField, StringField, IntegerField, SelectField, TextAreaField
from wtforms.validators import DataRequired, Length, Regexp, NumberRange
from school.config import Config
from school.models import CourseType


class EditCourseForm(Form):
    pass


class AddCourseForm(Form):
    pass


class TeacherAddCourseForm(Form):
    name = StringField("Name", validators=[
        DataRequired(),
        Length(min=Config.APP_COURSE_NAME_MIN, max=Config.APP_COURSE_NAME_MAX),
        Regexp(r'^[a-zA-Z0-9 ]+$')])
    degree_id = SelectField("Degree", coerce=int, validators=[DataRequired()], choices=[])
    semester_id = SelectField("Semester", coerce=int, validators=[DataRequired()], choices=[])

    submit = SubmitField("Add Optional Course")


class CDEditCourseForm(TeacherAddCourseForm):
    type_id = SelectField("Type", coerce=int, validators=[DataRequired()],
                          choices=[(CourseType.OPTIONAL, "Optional"), (CourseType.OTHER_OPTIONAL, "Other Optional")])
    package = SelectField("Package Nr", coerce=int, validators=[DataRequired()], choices=[(i, i) for i in range(1, 6)])
    min_students = IntegerField("Min Students", validators=[DataRequired()])
    max_students = IntegerField("Max Students", validators=[DataRequired()])
    credits = IntegerField("Credits", validators=[DataRequired(),
                                                  NumberRange(min=0, max=Config.APP_COURSE_CREDITS * 2)])
    approval_reason = TextAreaField("Reason")
    is_approved = BooleanField("Approved")

    submit = SubmitField("Edit Optional Course")

school/__init__.py
import os

from flask import Flask, render_template, url_for
from .frontend import frontend
from .config import Config
from .extensions import *
from .user import User, user
from .course import course
from .admin import admin
from .statistics import statistics


def create_app():
    app = Flask(__name__)

    # configure app
    app.config.from_object(Config)

    # configure extensions
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)
    toolbar.init_app(app)
    app.jinja_env.add_extension('jinja2.ext.do')

    # default login page, see https://flask-login.readthedocs.org/en/latest/#customizing-the-login-process
    login_manager.login_view = "frontend.login"

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    # configure blueprints
    blueprints = [frontend, user, course, admin, statistics]
    for blueprint in blueprints:
        app.register_blueprint(blueprint)

    # handle common error pages
    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template("errors/403.html"), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("errors/404.html"), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template("errors/500.html"), 500

    # static url cache buster, see http://flask.pocoo.org/snippets/40/
    @app.context_processor
    def override_url_for():
        return {"url_for": dated_url_for}

    def dated_url_for(endpoint, **values):
        if endpoint == 'static':
            filename = values.get('filename', None)
            if filename:
                file_path = os.path.join(app.root_path, endpoint, filename)
                values['q'] = int(os.stat(file_path).st_mtime)
        return url_for(endpoint, **values)

    return app

school/admin/__init__.py
# contains any CRUD not related to strictly editing users info and courses info
from .views import admin

school/admin/views.py
from flask.ext.login import login_required, current_user
from flask import Blueprint, render_template, flash, redirect, url_for, request
from school.decorators import role_required
from school.config import FLASH_SUCCESS, FLASH_ERROR
from school.models import *
from school.user import User

admin = Blueprint('admin', __name__)

@admin.route("/semesters")
@login_required
@role_required(admin=True)
def semesters():
    return "TODO"

# TODO add all the other views

school/course/__init__.py
# -*- coding: utf-8 -*-
from .views import course

school/course/views.py
from flask.ext.login import login_required, current_user
from flask import Blueprint, render_template, flash, redirect, url_for, request
from school.decorators import role_required
from school.config import FLASH_SUCCESS, FLASH_ERROR
from school.models import *
from school.user import User
from school.util import is_integer
from .forms import TeacherAddCourseForm, CDEditCourseForm

course = Blueprint('course', __name__)


@course.route('/see_courses', methods=['GET', 'POST'])
@course.route('/see_courses/<int:semester_id>', methods=['GET', 'POST'])
@login_required
def see_courses(semester_id=None):
    if current_user.is_student():

        period = current_user.get_default_period()
        degree = period.degree
        semesters = User.get_semesters_for_period(period)
        group = current_user.get_group(period)
        year, sem_nr = User.get_current_year_semester(semesters)

        if semester_id is None:  # use default, all semesters, enrolled with contract
            semester = None
            courses_enrolled = current_user.get_courses_enrolled(degree)
        else:  # has semester from url
            semester = Semester.get_by_id(semester_id)
            has_contract = current_user.has_contract_signed(semester, degree)
            courses_enrolled = []
            if has_contract:  # only display signed contracts for that semester
                courses_enrolled = current_user.get_courses_enrolled_semester(semester, degree)

        return render_template("course/see_courses.html",
                               semesters=semesters,
                               courses_enrolled=courses_enrolled,
                               selected_semester=semester,
                               group=group,
                               degree=degree,
                               year=year,
                               semester_nr=sem_nr)
    elif current_user.is_admin():

        departments = Department.query.order_by("name").all()

        seen_depts = set()
        depts = []
        courses_depts = []

        for department in departments:
            if department.name not in seen_depts:
                seen_depts.add(department.name)
                depts.append(department.name)

            for degree in department.degrees:
                for course in degree.courses:
                    courses_depts.append({
                        "course": course.name,
                        "department": department.name
                    })

        return render_template("course/see_courses.html", total=courses_depts, depts=depts)

    elif current_user.is_teacher():
        # TODO group by semester
        courses = [teach.course for teach in current_user.teaches.all() if teach.course.is_approved]

        return render_template("course/see_courses.html", courses=courses)

    elif current_user.is_chief_department():
        department = current_user.get_department_cd()

        courses_depts = []
        for degree in department.degrees:
            for course in degree.courses:
                courses_depts.append({
                    "course": course.name,
                    "department": department.name
                })

        courses = [teach.course for teach in current_user.teaches.all() if teach.course.is_approved]

        return render_template("course/see_courses.html", total=courses_depts, dp=department, courses=courses)


@course.route('/upload_course_results/<int:course_id>/<int:semester_id>', methods=['GET', 'POST'])
@course.route('/upload_course_results/<int:course_id>/', methods=['GET', 'POST'])
@login_required
@role_required(teacher=True, cd=True)
def upload_course_results(course_id, semester_id=None):
    selected_course = Course.get_by_id(course_id)

    # form submitted, redirect
    if request.method == 'POST':
        # validate
        if 'semester_id' not in request.form:
            flash("upload_course_results semester_id is missing", FLASH_ERROR)
            return redirect(url_for('course.see_courses'))
        if not is_integer(request.form['semester_id']):
            flash("upload_course_results semester_id is not an integer", FLASH_ERROR)
            return redirect(url_for('course.see_courses'))

        return redirect(url_for('course.upload_course_results',
                                course_id=selected_course.id,
                                semester_id=int(request.form['semester_id'])))

    # display students and grades
    if semester_id is not None:
        selected_semester = Semester.get_by_id(semester_id)
        students_enrolled = Enrollment.query.filter_by(course_id=course_id, semester_id=semester_id).all()

        # group students in Groups :P
        groups = {}
        for enroll in students_enrolled:
            g = enroll.student.get_group(enroll.student.get_default_period())
            if g.name not in groups:
                groups[g.name] = []

            groups[g.name].append(enroll)

        return render_template("course/upload_course_results.html",
                               students_enrolled=students_enrolled,
                               semesters=selected_course.semesters,
                               selected_course=selected_course,
                               selected_semester=selected_semester,
                               groups=groups,
                               groups_keys=sorted(groups.keys()))

    # use default to be first semester
    if not selected_course.semesters:
        flash("Selected course does not have any semesters", FLASH_ERROR)
        return redirect(url_for('course.see_courses'))

    return redirect(url_for('course.upload_course_results',
                            course_id=selected_course.id,
                            semester_id=selected_course.semesters[0].id))


@course.route('/save_grade/<int:course_id>/<int:semester_id>', methods=['POST'])
@login_required
@role_required(teacher=True, cd=True)
def save_grade(course_id, semester_id):

    # TODO validate
    selected_semester = Semester.get_by_id(semester_id)
    selected_course = Course.get_by_id(course_id)
    return_path = redirect(
        url_for('course.upload_course_results', course_id=selected_course.id, semester_id=selected_semester.id))

    students_enrolled = Enrollment.query.filter_by(course_id=course_id, semester_id=semester_id).all()
    for enrolled in students_enrolled:
        student_id_str = str(enrolled.student_id)
        if student_id_str not in request.form:
            flash("save_grade missing argument", FLASH_ERROR)
            return return_path

        if request.form[student_id_str].isnumeric():
            grade = int(request.form[student_id_str])
            if 0 <= grade <= 10:  # save new grade
                enrolled.grade = grade
                db.session.add(enrolled)
                db.session.commit()
            else:
                flash("A grade should be between 0 and 10", FLASH_ERROR)
                return return_path
        else:
            flash("A grade should be numeric", FLASH_ERROR)
            return return_path

    flash("Grade updated", FLASH_SUCCESS)
    return return_path


@course.route('/contract/start/<int:semester_id>')
@course.route('/contract/action/<int:semester_id>/<int:action>/<int:course_id>', methods=['GET', 'POST'])
@login_required
@role_required(student=True)
def contract_action(semester_id, action=None, course_id=None):
    # get info from database
    semester = Semester.get_by_id(semester_id)
    period = current_user.get_default_period()
    degree = period.degree
    has_contract = current_user.has_contract_signed(semester, degree)
    courses_enrolled = current_user.get_courses_enrolled_semester(semester, degree)
    return_path = redirect(url_for('course.contract', semester_id=semester_id))

    # validate
    if has_contract:
        flash("Your contract is already signed for that semester", FLASH_ERROR)
        return return_path

    # start contract
    if action is None and course_id is None:
        if courses_enrolled:
            flash("You already started the temporary contract for that semester", FLASH_ERROR)
            return return_path

        # add initial obligatory courses
        obligatory_courses = semester.filter_obligatory_courses(degree)
        courses_all = [c for e, c in current_user.get_courses_enrolled(degree)]
        for c in obligatory_courses:
            if c not in courses_all:  # only add course from current year
                db.session.add(Enrollment(student=current_user, semester=semester, course=c))
        db.session.commit()

        flash("Added obligatory courses", FLASH_SUCCESS)
        return return_path

    # add or remove course from contract
    course_add = Course.get_by_id(course_id)
    if not course_add.is_optional:
        flash("Course is not optional", FLASH_ERROR)
        return return_path

    courses = [x[1] for x in courses_enrolled]
    if action == 1:  # add course
        if course_add in courses:  # validate
            flash("You are already enrolled for that course", FLASH_ERROR)
            return return_path

        db.session.add(Enrollment(student=current_user, semester=semester, course=course_add, priority=1))
        db.session.commit()

        flash("Course Added", FLASH_SUCCESS)
    elif action == 2:  # remove course
        if course_add not in courses:  # validate
            flash("You are not enrolled in that course", FLASH_ERROR)
            return return_path

        db.session.delete(
            Enrollment.query.filter_by(student=current_user, semester=semester, course=course_add).first())
        db.session.commit()

        flash("Course Removed", FLASH_SUCCESS)
    elif action == 3:  # set course priority
        if course_add not in courses:  # validate
            flash("You are not enrolled in that course", FLASH_ERROR)
            return return_path
        if request.method != 'POST':

school/frontend/__init__.py
# -*- coding: utf-8 -*-

from .views import frontend
from .forms import LoginForm

school/statistics/__init__.py
from .views import statistics

school/user/__init__.py
# -*- coding: utf-8 -*-

from .views import user
from .models import User

school/user/views.py
from flask.ext.login import login_required, current_user
from flask import Blueprint, render_template, flash, redirect, url_for
from .forms import ChangePasswordForm, EditUserForm, AddUserForm
from .models import User
from school.config import FLASH_SUCCESS, FLASH_ERROR
from school.decorators import role_required
from school.extensions import db, mail
from flask_mail import Message

user = Blueprint('user', __name__)

# the root of our website
@user.route('/')
@login_required
def index():
    return render_template("user/index.html")


@user.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        flash('Password changed successfully.', FLASH_SUCCESS)
        current_user.password = form.new_password.data

        db.session.add(current_user)
        db.session.commit()

        msg = Message('Your password has changed', sender='academicinfo.seproject@gmail.com',
                      recipients=[current_user.email])
        msg.html = render_template('emails/changed_password_email.html', user=current_user)
        mail.send(msg)
        return form.redirect("user.index")

    return render_template('user/change_password.html', form=form)


@user.route('/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
@role_required(admin=True, cd=True)
def profile(user_id):
    user_instance = User.get_by_id(user_id)
    form = EditUserForm(obj=user_instance)
    if form.validate_on_submit():
        flash("Updated user details", FLASH_SUCCESS)

        form.populate_obj(user_instance)

        db.session.add(user_instance)
        db.session.commit()

    return render_template("user/user.html", user=user_instance, form=form)


@user.route('/user/delete/<int:user_id>')
@login_required
@role_required(admin=True, cd=True)
def delete(user_id):
    user_instance = User.get_by_id(user_id)
    if user_instance.id == current_user.id:
        flash("You can not delete yourself ;)", FLASH_ERROR)
        return redirect(url_for("user.users"))

    flash("User %s deleted" % user_instance.username, FLASH_SUCCESS)

    db.session.delete(user_instance)
    db.session.commit()

    return redirect(url_for("user.users"))


@user.route('/users', methods=['GET', 'POST'])
@login_required
@role_required(admin=True, cd=True)
def users():
    # CD can edit users only in this department

    form = AddUserForm()
    if form.validate_on_submit():  # add user

        # update database
        user_instance = User()
        form.populate_obj(user_instance)
        db.session.add(user_instance)
        db.session.commit()

        # update view
        form = AddUserForm()
        flash("User added", FLASH_SUCCESS)

    users_list = User.query.all()
    return render_template("user/users.html", users=users_list, add_form=form)

school/templates/user/change_password.html
{% from "macros/form.html" import render_form %}
{% extends 'base.html' %}
{% set page_title = 'Change Password' %}

{% block body %}
<h2 class="text-center">Change password</h2><hr>
<div class="col-md-4 col-md-offset-4">
    <div>
        {{ render_form(url_for('user.change_password'), form) }}
    </div>
</div>
{% endblock %}

school/templates/user/changed_password_email.html
{% block body %}

    <p>Hello {{ user.username }}!</p>

    <p>We wanted to let you know that your password was changed.</p>

    <p>If you did not perform this action, you can recover access by entering into the form at <a href="http://127.0.0.1:5000/password_reset">http://127.0.0.1:5000/password_reset</a>.</p>


{% endblock %}

school/templates/user/changepassword.html
{% from "macros/form.html" import render_form %}
{% extends 'base.html' %}
{% set page_title = 'Change Password' %}

{% block body %}
<h2 class="text-center">Change password</h2><hr>
<div class="col-md-4 col-md-offset-4">
    <div>
        {{ render_form(url_for('user.changepassword'), form) }}
    </div>
</div>
{% endblock %}

school/templates/user/index.html
{% extends 'base.html' %}
{% set page_title = 'School' %}

{% block body %}
    <h1 class="text-center">Hi, {{ current_user.realname }}</h1><hr>
    <div class="col-md-offset-3 col-md-6">
        <div class="list-group text-center">
            {% if current_user.is_student() %}
                <a href="{{ url_for('course.see_courses') }}" class="list-group-item">My courses</a>
                <a href="{{ url_for('course.contract') }}" class="list-group-item">Choose courses (contract)</a>
            {% else %}
                <a href="{{ url_for('course.see_courses') }}" class="list-group-item">See courses</a>
                {% if current_user.is_chief_department() or current_user.is_admin() %}
                    <a href="{{ url_for('course.establish_courses') }}" class="list-group-item">Manage optional courses</a>
                    <a href="{{ url_for('statistics.see_statistics') }}" class="list-group-item">See statistics</a>
                    <a href="{{ url_for('user.users') }}" class="list-group-item">Edit users</a></li>
                {% else %}
                    <a href="{{ url_for('course.establish_courses') }}" class="list-group-item">Add optional course</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}

school/templates/user/seeCourses.html
{% extends 'base.html' %}
{% set page_title = 'See courses' %}

{% block body %}
<form name="formSeeCourses" >
    <table cellspacing="0px" cellpadding="0px" style="width:100%">
        <tbody>
        <tr><td class="CourseSelector" >
            <select size="1" >
                {% for course in courses %}
                <option value="">{{ course.name }}</option>
                {% endfor %}
            </select>
            <input class="Button" type="submit" style="width:95px" value="Select course">
        </tr>
        </tbody>
    </table>

</form>

<br />

<tbody><tr valign="top">
          <td style="border: 1px solid black;" >
            <div style="height: 393px; width: 1182px; overflow: auto;">
              <table style="border: 1px solid black;" cellspacing="5px" cellpadding="5px" class="Projects">
                <tbody><tr style="border: 1px solid black;" >
                  <td class="Header" style="text-align: center; border: 1px solid black;">
                    Proiect
                  </td>
                  <td class="Header" style="text-align: center;border: 1px solid black;">
                    Deadline
                  </td>
                  <td class="Header" style="text-align: center;border: 1px solid black;">
                    Grade
                  </td>
                </tr>

                {% for project in projects %}
                <tr style="text-align: center;border: 1px solid black;" >
                    <td style="text-align: center;border: 1px solid black;" >
                      <a href="">
                          {{ project.name }}
                      </a>
                    </td>
                    <td style="text-align: center;border: 1px solid black;" >
                      {{ project.deadline }}
                    </td>
                    <td style="text-align: center;border: 1px solid black;">
                      &nbsp;
                        {{ project.grade }}

                    </td>
                  </tr>
                {% endfor %}

              </tbody></table>
            </div>
          </td>
        </tr>
      </tbody>
{% endblock %}

school/templates/user/user.html
{% from "macros/form.html" import render_form %}
{% extends 'base.html' %}
{% set page_title = 'User edit' %}

{% block body %}
    <h1 class="text-center">Edit user {{ user.username }}</h1><hr>
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            {{ render_form(url_for('user.profile', user_id=user.id), form) }}
        </div>
    </div>
{% endblock %}

school/templates/user/users.html
{% from "macros/form.html" import render_form %}
{% extends 'base.html' %}
{% set page_title = 'Users' %}

{% block body %}
    <h2 class="text-center">Add user</h2><hr>
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            {{ render_form(url_for('user.users'), add_form) }}
        </div>
    </div>
    <h2 class="text-center">Edit users</h2><hr>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped">
                <tr>
                    <th>#ID</th>
                    <th>Username</th>
                    <th>Real name</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Actions</th>
                </tr>
                {% for user in users %}
                    <tr>
                        <td><a href="{{ url_for('user.profile', user_id=user.id) }}">{{ user.id }}</a></td>
                        <td><a href="{{ url_for('user.profile', user_id=user.id) }}">{{ user.username }}</a></td>
                        <td>{{ user.realname }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.role_to_str() }}</td>
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-danger" href="{{ url_for('user.delete', user_id=user.id) }}">Delete</a>
                                <a class="btn btn-primary" href="{{ url_for('user.profile', user_id=user.id) }}">Edit</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}