school/admin/forms.py
from flask_wtf import Form
from wtforms import PasswordField, SubmitField, ValidationError, StringField, SelectField
from wtforms.validators import DataRequired, EqualTo, Email
from school.forms import RedirectForm
from flask.ext.login import current_user

class EditSemesterForm(Form):
    pass

class AddSemesterForm(Form):
    pass

class EditGroupForm(Form):
    pass

class AddGroupForm(Form):
    pass

class EditDepartmentForm(Form):
    pass

class AddDepartmentForm(Form):
    pass

class EditLanguageForm(Form):
    pass

class AddLanguageForm(Form):
    pass

# TODO maybe add teaches here?

school/__init__.py
import os

from flask import Flask, render_template, url_for
from .frontend import frontend
from .config import Config
from .extensions import *
from .user import User, user
from .course import course
from .admin import admin
from .statistics import statistics


def create_app():
    app = Flask(__name__)

    # configure app
    app.config.from_object(Config)

    # configure extensions
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)
    toolbar.init_app(app)
    app.jinja_env.add_extension('jinja2.ext.do')

    # default login page, see https://flask-login.readthedocs.org/en/latest/#customizing-the-login-process
    login_manager.login_view = "frontend.login"

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    # configure blueprints
    blueprints = [frontend, user, course, admin, statistics]
    for blueprint in blueprints:
        app.register_blueprint(blueprint)

    # handle common error pages
    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template("errors/403.html"), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("errors/404.html"), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template("errors/500.html"), 500

    # static url cache buster, see http://flask.pocoo.org/snippets/40/
    @app.context_processor
    def override_url_for():
        return {"url_for": dated_url_for}

    def dated_url_for(endpoint, **values):
        if endpoint == 'static':
            filename = values.get('filename', None)
            if filename:
                file_path = os.path.join(app.root_path, endpoint, filename)
                values['q'] = int(os.stat(file_path).st_mtime)
        return url_for(endpoint, **values)

    return app

school/admin/__init__.py
# contains any CRUD not related to strictly editing users info and courses info
from .views import admin

school/admin/views.py
from flask.ext.login import login_required, current_user
from flask import Blueprint, render_template, flash, redirect, url_for, request
from school.decorators import role_required
from school.config import FLASH_SUCCESS, FLASH_ERROR
from school.models import *
from school.user import User

admin = Blueprint('admin', __name__)

@admin.route("/semesters")
@login_required
@role_required(admin=True)
def semesters():
    return "TODO"

# TODO add all the other views

school/course/__init__.py
# -*- coding: utf-8 -*-
from .views import course

school/course/views.py
from flask.ext.login import login_required, current_user
from flask import Blueprint, render_template, flash, redirect, url_for, request
from school.decorators import role_required
from school.config import FLASH_SUCCESS, FLASH_ERROR
from school.models import *
from school.user import User
from school.util import is_integer
from .forms import TeacherAddCourseForm, CDEditCourseForm

course = Blueprint('course', __name__)


@course.route('/see_courses', methods=['GET', 'POST'])
@course.route('/see_courses/<int:semester_id>', methods=['GET', 'POST'])
@login_required
def see_courses(semester_id=None):
    if current_user.is_student():

        period = current_user.get_default_period()
        degree = period.degree
        semesters = User.get_semesters_for_period(period)
        group = current_user.get_group(period)
        year, sem_nr = User.get_current_year_semester(semesters)

        if semester_id is None:  # use default, all semesters, enrolled with contract
            semester = None
            courses_enrolled = current_user.get_courses_enrolled(degree)
        else:  # has semester from url
            semester = Semester.get_by_id(semester_id)
            has_contract = current_user.has_contract_signed(semester, degree)
            courses_enrolled = []
            if has_contract:  # only display signed contracts for that semester
                courses_enrolled = current_user.get_courses_enrolled_semester(semester, degree)

        return render_template("course/see_courses.html",
                               semesters=semesters,
                               courses_enrolled=courses_enrolled,
                               selected_semester=semester,
                               group=group,
                               degree=degree,
                               year=year,
                               semester_nr=sem_nr)
    elif current_user.is_admin():

        departments = Department.query.order_by("name").all()

        seen_depts = set()
        depts = []
        courses_depts = []

        for department in departments:
            if department.name not in seen_depts:
                seen_depts.add(department.name)
                depts.append(department.name)

            for degree in department.degrees:
                for course in degree.courses:
                    courses_depts.append({
                        "course": course.name,
                        "department": department.name
                    })

        return render_template("course/see_courses.html", total=courses_depts, depts=depts)

    elif current_user.is_teacher():
        # TODO group by semester
        courses = [teach.course for teach in current_user.teaches.all() if teach.course.is_approved]

        return render_template("course/see_courses.html", courses=courses)

    elif current_user.is_chief_department():
        department = current_user.get_department_cd()

        courses_depts = []
        for degree in department.degrees:
            for course in degree.courses:
                courses_depts.append({
                    "course": course.name,
                    "department": department.name
                })

        courses = [teach.course for teach in current_user.teaches.all() if teach.course.is_approved]

        return render_template("course/see_courses.html", total=courses_depts, dp=department, courses=courses)


@course.route('/upload_course_results/<int:course_id>/<int:semester_id>', methods=['GET', 'POST'])
@course.route('/upload_course_results/<int:course_id>/', methods=['GET', 'POST'])
@login_required
@role_required(teacher=True, cd=True)
def upload_course_results(course_id, semester_id=None):
    selected_course = Course.get_by_id(course_id)

    # form submitted, redirect
    if request.method == 'POST':
        # validate
        if 'semester_id' not in request.form:
            flash("upload_course_results semester_id is missing", FLASH_ERROR)
            return redirect(url_for('course.see_courses'))
        if not is_integer(request.form['semester_id']):
            flash("upload_course_results semester_id is not an integer", FLASH_ERROR)
            return redirect(url_for('course.see_courses'))

        return redirect(url_for('course.upload_course_results',
                                course_id=selected_course.id,
                                semester_id=int(request.form['semester_id'])))

    # display students and grades
    if semester_id is not None:
        selected_semester = Semester.get_by_id(semester_id)
        students_enrolled = Enrollment.query.filter_by(course_id=course_id, semester_id=semester_id).all()

        # group students in Groups :P
        groups = {}
        for enroll in students_enrolled:
            g = enroll.student.get_group(enroll.student.get_default_period())
            if g.name not in groups:
                groups[g.name] = []

            groups[g.name].append(enroll)

        return render_template("course/upload_course_results.html",
                               students_enrolled=students_enrolled,
                               semesters=selected_course.semesters,
                               selected_course=selected_course,
                               selected_semester=selected_semester,
                               groups=groups,
                               groups_keys=sorted(groups.keys()))

    # use default to be first semester
    if not selected_course.semesters:
        flash("Selected course does not have any semesters", FLASH_ERROR)
        return redirect(url_for('course.see_courses'))

    return redirect(url_for('course.upload_course_results',
                            course_id=selected_course.id,
                            semester_id=selected_course.semesters[0].id))


@course.route('/save_grade/<int:course_id>/<int:semester_id>', methods=['POST'])
@login_required
@role_required(teacher=True, cd=True)
def save_grade(course_id, semester_id):

    # TODO validate
    selected_semester = Semester.get_by_id(semester_id)
    selected_course = Course.get_by_id(course_id)
    return_path = redirect(
        url_for('course.upload_course_results', course_id=selected_course.id, semester_id=selected_semester.id))

    students_enrolled = Enrollment.query.filter_by(course_id=course_id, semester_id=semester_id).all()
    for enrolled in students_enrolled:
        student_id_str = str(enrolled.student_id)
        if student_id_str not in request.form:
            flash("save_grade missing argument", FLASH_ERROR)
            return return_path

        if request.form[student_id_str].isnumeric():
            grade = int(request.form[student_id_str])
            if 0 <= grade <= 10:  # save new grade
                enrolled.grade = grade
                db.session.add(enrolled)
                db.session.commit()
            else:
                flash("A grade should be between 0 and 10", FLASH_ERROR)
                return return_path
        else:
            flash("A grade should be numeric", FLASH_ERROR)
            return return_path

    flash("Grade updated", FLASH_SUCCESS)
    return return_path


@course.route('/contract/start/<int:semester_id>')
@course.route('/contract/action/<int:semester_id>/<int:action>/<int:course_id>', methods=['GET', 'POST'])
@login_required
@role_required(student=True)
def contract_action(semester_id, action=None, course_id=None):
    # get info from database
    semester = Semester.get_by_id(semester_id)
    period = current_user.get_default_period()
    degree = period.degree
    has_contract = current_user.has_contract_signed(semester, degree)
    courses_enrolled = current_user.get_courses_enrolled_semester(semester, degree)
    return_path = redirect(url_for('course.contract', semester_id=semester_id))

    # validate
    if has_contract:
        flash("Your contract is already signed for that semester", FLASH_ERROR)
        return return_path

    # start contract
    if action is None and course_id is None:
        if courses_enrolled:
            flash("You already started the temporary contract for that semester", FLASH_ERROR)
            return return_path

        # add initial obligatory courses
        obligatory_courses = semester.filter_obligatory_courses(degree)
        courses_all = [c for e, c in current_user.get_courses_enrolled(degree)]
        for c in obligatory_courses:
            if c not in courses_all:  # only add course from current year
                db.session.add(Enrollment(student=current_user, semester=semester, course=c))
        db.session.commit()

        flash("Added obligatory courses", FLASH_SUCCESS)
        return return_path

    # add or remove course from contract
    course_add = Course.get_by_id(course_id)
    if not course_add.is_optional:
        flash("Course is not optional", FLASH_ERROR)
        return return_path

    courses = [x[1] for x in courses_enrolled]
    if action == 1:  # add course
        if course_add in courses:  # validate
            flash("You are already enrolled for that course", FLASH_ERROR)
            return return_path

        db.session.add(Enrollment(student=current_user, semester=semester, course=course_add, priority=1))
        db.session.commit()

        flash("Course Added", FLASH_SUCCESS)
    elif action == 2:  # remove course
        if course_add not in courses:  # validate
            flash("You are not enrolled in that course", FLASH_ERROR)
            return return_path

        db.session.delete(
            Enrollment.query.filter_by(student=current_user, semester=semester, course=course_add).first())
        db.session.commit()

        flash("Course Removed", FLASH_SUCCESS)
    elif action == 3:  # set course priority
        if course_add not in courses:  # validate
            flash("You are not enrolled in that course", FLASH_ERROR)
            return return_path
        if request.method != 'POST':

school/frontend/__init__.py
# -*- coding: utf-8 -*-

from .views import frontend
from .forms import LoginForm

school/frontend/views.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, current_app
from flask.ext.login import login_required, logout_user, current_user, login_user
from .forms import LoginForm, PasswordResetForm, PasswordResetSubmitForm
from school.config import FLASH_SUCCESS, FLASH_INFO, FLASH_WARNING, FLASH_ERROR
from school.user.models import User
from school.extensions import *
from flask.ext.mail import Message

frontend = Blueprint('frontend', __name__)


@frontend.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated():  # user is already logged in
        flash("You are already logged in", FLASH_WARNING)
        return redirect(url_for('user.index'))

    form = LoginForm()
    if form.validate_on_submit():
        if form.remember_me.data:
            login_user(form.user, remember=True)
        else:
            login_user(form.user)

        return form.redirect("user.index")

    return render_template('frontend/login.html', form=form)


@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', FLASH_INFO)

    return redirect(url_for("frontend.login"))


@frontend.route('/password_reset', methods=["GET", "POST"])
def password_reset():
    token = request.args.get('token')

    # display password request form
    if token is None:
        password_reset_form = PasswordResetForm()
        if password_reset_form.validate_on_submit():
            email = password_reset_form.email.data
            user = password_reset_form.user
            if user is not None:

                # user has already a token present
                if User.verify_token(user.active_token):
                    flash("This email has a active reset password link still active. Please check your email spam folder.", FLASH_ERROR)
                    return render_template('frontend/password_reset.html', form=password_reset_form)

                # generate new token
                token = user.get_token()
                user.active_token = token
                db.session.add(user)
                db.session.commit()

                # send mail
                msg = Message('Reset password', sender='academicinfo.seproject@gmail.com', recipients=[email])
                msg.html = render_template('emails/password_reset_email.html', user=user, token=token)
                mail.send(msg)

                return render_template('frontend/password_reset_confirmation_sent.html')
        return render_template('frontend/password_reset.html', form=password_reset_form)

    # a token was given
    verified_result = User.verify_token(token)

    # given token is not valid
    if verified_result is None or verified_result.active_token is None:
        flash("It looks like you clicked on an invalid password reset link. Please try again.", FLASH_ERROR)
        password_reset_form = PasswordResetForm()
        return render_template('frontend/password_reset.html', form=password_reset_form)

    # the token is good
    password_submit_form = PasswordResetSubmitForm()
    if password_submit_form.validate_on_submit():
        # we make sure that the token is used only once
        verified_result.password = password_submit_form.new_password.data
        verified_result.active_token = None
        db.session.add(verified_result)
        db.session.commit()

        # send mail
        msg = Message('Your password has changed',
                      sender='academicinfo.seproject@gmail.com', recipients=[verified_result.email])
        msg.html = render_template('emails/changed_password_email.html', user=verified_result)
        mail.send(msg)

        flash("New password set successfully.", FLASH_SUCCESS)
        return redirect(url_for("frontend.login"))

    return render_template('frontend/password_reset_submit.html', token=token,
                           password_submit_form=password_submit_form)

school/statistics/__init__.py
from .views import statistics

school/user/__init__.py
# -*- coding: utf-8 -*-

from .views import user
from .models import User

school/templates/course/contract.html
{% from "macros/form.html" import render_form %}
{% extends 'base.html' %}
{% set page_title = 'Contract' %}

{% block body %}
    <h1 class="text-center">Contract</h1><hr>
    <div class="row">
        <div class="col-md-offset-3 col-md-8">
            <button class="btn btn-default" disabled="disabled"> Degree: {{ degree.name }} </button>
            <button class="btn btn-default" disabled="disabled"> Group: {{ group.name }} </button>
            <button class="btn btn-default" disabled="disabled"> Current year: {{ year }} </button>
            <button class="btn btn-default" disabled="disabled"> Current semester: {{ semester_nr }} </button>
        </div>
    </div><hr>
    <div class="col-md-2">
        <div class="btn-group" id="semesters-pick">
            {% for semester in semesters %}
                <a data-id="{{ semester.id }}" href="{{ url_for('course.contract', semester_id=semester.id) }}"
                    class="btn btn-default{% if semester_sel.id == semester.id %} active{% endif %}">
                    Semester {{ loop.index }}, Year {{ semester.year }}
                </a>
            {% endfor %}
        </div>
    </div>
    {% if has_contract %}
        <div class="col-md-10">
            <table class="table table-striped">
                <tr>
                    <th>#</th>
                    <th>Code</th>
                    <th>Name Course</th>
                    <th>Type</th>
                    <th>Grade</th>
                </tr>
                {% for enrolled, course in courses_enrolled %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ course.get_code() }}</td>
                        <td>{{ course.name }}</td>
                        <td>{{ course.type_to_str().title() }}</td>
                        <td>{{ enrolled.grade }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% elif not courses_enrolled %}
        <div class="col-md-4 col-md-offset-2">
            <p class="text-center">Contract is empty, start building temporary contract</p>
            <a class="btn btn-default col-md-offset-3" href="{{ url_for("course.contract_action", semester_id=semester_sel.id) }}">
                Start Building Contract
            </a>
        </div>
    {% else %}
        <div class="col-md-10">
            <h3>All courses you can choose</h3>
            <table class="table table-bordered table-striped" id="table-all-courses">
                <tr>
                    <th class="col-md-1">Package</th>
                    <th class="col-md-1">Type</th>
                    <th>Name</th>
                    <th>Code</th>
                    <th class="col-md-1">Credits</th>
                    <th>Enrolled/Max</th>
                    <th>Actions</th>
                </tr>
                {% for course in courses_semester %}
                    <tr>
                        <td>
                            {% if course.is_optional %}
                                {{ course.package }}
                            {% endif %}
                        </td>
                        <td>
                            <span data-toggle="tooltip" data-placement="top" title="{{ course.type_to_str().title() }}">
                                {{ course.type_id }}
                            </span>
                        </td>
                        <td>{{ course.name }}</td>
                        <td>{{ course.get_code() }}</td>
                        <td>{{ course.credits }}</td>
                        <td>{{ course.get_nr_enrolled(semester_sel.id) }}/{{ course.get_max_str() }}</td>
                        <td>
                             {% if course.is_optional and not course.is_in_contract %}
                                <a href="{{ url_for('course.contract_action', semester_id=semester_sel.id, action=1, course_id=course.id) }}"
                                   class="btn btn-primary btn-block" data-toggle="tooltip" data-placement="top" title="You can change priority after you add it">
                                    {% if course.package in packages %}
                                        Add preference to package
                                    {% else %}
                                        Add
                                    {% endif %}
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-md-10 col-md-offset-2">
            <h3>Temporary contract</h3>
            <table class="table table-bordered table-striped tabble-c">
                <tr>
                    <th class="col-md-1">Package</th>
                    <th class="col-md-1">Type</th>
                    <th>Name Course</th>
                    <th class="col-md-1">Code</th>
                    <td class="col-md-3">
                        <span data-toggle="tooltip" data-placement="top" title="What is your priority for this optional course. Lower priority means it is higher ranked">Priority</span>
                    </td>
                    <th class="col-md-2">Actions</th>
                </tr>
                {% for enrolled, course in courses_enrolled %}
                    <tr>
                        <td>
                            {% if course.is_optional %}
                            <span data-toggle="tooltip" data-placement="top" title="Priority: {{ enrolled.priority }}">
                                {{ course.package }}
                            </span>
                            {% endif %}
                        </td>
                        <td>
                            <span data-toggle="tooltip" data-placement="top" title="{{ course.type_to_str().title() }}">
                                {{ course.type_id }}
                            </span>
                        </td>
                        <td>{{ course.name }}</td>
                        <td>{{ course.get_code() }}</td>
                        <td>
                            {% if course.is_optional %}
                                 {% if packages[course.package]|length > 1 %}
                                     <form method="post" action="{{ url_for('course.contract_action', semester_id=semester_sel.id, action=3, course_id=course.id) }}">
                                         <div class="input-group">
                                             <input type="number" name="priority" min="1" max="9"
                                                    class="pos-integer form-control input-sm" value="{{ enrolled.priority }}">
                                             <span class="input-group-btn">
                                                 <input type="submit" class="btn btn-sm btn-success" value="Change Priority">
                                             </span>
                                         </div>
                                     </form>
                                 {% else %}
                                     {{ enrolled.priority }}</td>
                                 {% endif %}
                            {% endif %}
                        <td>
                        <div class="btn-group">
                            {% if course.is_optional %}
                                 <a href="{{ url_for('course.contract_action', semester_id=semester_sel.id, action=2, course_id=course.id) }}"
                                       class="btn btn-danger">Remove</a>
                            {% endif %}
                        </div>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% endif %}
{% endblock %}
{% block js %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/courses.js') }}"></script>
{% endblock %}

school/templates/course/edit_optional_course.html
{% from "macros/form.html" import render_form %}
{% extends 'base.html' %}
{% set page_title = 'Edit Optional Coruse' %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default pull-left" href="{{ url_for('course.establish_courses') }}">Back</a>
            <h1 class="text-center">Edit Optional Course</h1>
        </div>
    </div><hr>
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            {{ render_form(url_for('course.edit_optional_course', course_id=course.id), form, submit_block=True) }}
        </div>
    </div>
{% endblock %}
{% block js %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/courses.js') }}"></script>
{% endblock %}

school/templates/course/upload_course_results.html
{% extends 'base.html' %}
{% set page_title = 'Upload Course Results' %}

{% block body %}
<div class="col-md-4 col-md-push-4 text-center">
    <form method="post" action="{{ url_for("course.upload_course_results", course_id=selected_course.id) }}">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <select class="form-control" size="1" name="semester_id" onchange="this.form.submit()">
                    <optgroup label="Choose a semester">
                    {% for semester in semesters %}
                        <option value="{{ semester.id }}" {% if selected_semester == semester %}selected{% endif %}>
                            {{ semester.name }}
                        </option>
                    {% endfor %}
                    </optgroup>
                </select>
            </div>
        </div>
    </form>

    <h3>
        <span class="label label-default">{{ selected_course.name }}</span>
        <span class="label label-default">{{ selected_semester.name }}</span>
    </h3><hr>

    {% if students_enrolled %}
    <form method="post" action="{{ url_for("course.save_grade", course_id=selected_course.id, semester_id=selected_semester.id) }}">
        <table class="table table-bordered">
            {% for name in groups_keys %}
            <tr>
                <th>Name</th>
                <th>Grade</th>
                <th>{{ name }}</th>
            </tr>
                {% for enrolled in groups[name] %}
                    <tr>
                        <td>{{ enrolled.student.realname }} </td>
                        <td>
                            <input type="number" min="0" max="10" class="pos-integer form-control" name="{{ enrolled.student.id }}" placeholder="Grade" value="{{ enrolled.grade }}">
                        </td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </table>
        <input type="submit" class="btn btn-primary" value="Save">
    </form>
    {% endif %}
</div>
{% endblock %}
{% block js %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/courses.js') }}"></script>
{% endblock %}